baseURL = 'https://vincenthardouin.dev/'
languageCode = 'FR-fr'
defaultContentLanguage = 'fr'
theme = "symbol"
title = 'Vincent Hardouin'
enableInlineShortcodes = true

[params]
  author = 'Vincent Hardouin'
  description = 'Blog de tutorials, humeurs, … sur des sujets tech.'
  mainSections = ['posts', 'external_posts']

  [params.comments]
    enabled = true
    provider = "giscus"

    commentable = {page = false, posts = true}

    [params.comments.giscus]
      repo = "VincentHardouin/blog"
      repo_id = "MDEwOlJlcG9zaXRvcnk0MDM2OTk5MTk="
      category = "Announcements"
      category_id = "DIC_kwDOGA_4z84CWyji"
      mapping = "title"
      strict = 0
      label = "comment"
      theme = "preferred_color_scheme"
      input_position = "bottom"
      emit_metadata = 0
      reactions_enabled = 1


[markup]
  [markup.highlight]
    noclasses = false

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "À propos"
    url = "/a-propos"
    weight = 2