baseURL = 'https://vincenthardouin.dev/'
languageCode = 'FR-fr'
defaultContentLanguage = 'fr'
theme = "symbol"
title = 'Vincent Hardouin'
enableInlineShortcodes = true

[params]
  author = 'Vincent Hardouin'
  description = 'Blog de tutorials, humeurs, … sur des sujets tech.'

[markup]
  [markup.highlight]
    noclasses = false

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "À propos"
    url = "/a-propos"
    weight = 2
