baseURL = 'https://vincenthardouin.dev/'
languageCode = 'fr-fr'
theme = "symbol"
title = 'Vincent Hardouin'

[params]
  author = 'Vincent Hardouin'

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "À propos"
    url = "/a-propos"
    weight = 2
