name: cd

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ 'deploy' ]
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install tcardgen
        run: go install github.com/VincentHardouin/tcardgen@feat-allow-disabled

      - name: Generate Card
        run: ./og-card/generate.sh

      - name: Build
        run: hugo --minify
        env:
          HUGO_PLAUSIBLE_URL: ${{ secrets.PLAUSIBLE_URL }}
          HUGO_DOMAIN: vincenthardouin.dev

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19
          extra_plugins: |
            @semantic-release/changelog@6.0.2
            @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: vincenthardouin.dev
