name: cd

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ 'deploy' ]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - run: npm ci
      - run: npm test
      - run: npm run generate
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          STRAPI_URL: ${{ secrets.STRAPI_URL }}
          PLAUSIBLE_URL: ${{ secrets.PLAUSIBLE_URL }}

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: vincenthardouin.dev
