name: cd

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ 'deploy' ]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify
        env:
          HUGO_PLAUSIBLE_URL: ${{ secrets.PLAUSIBLE_URL }}
          DOMAIN_URL: 'vincenthardouin.dev'

      - name: Release
        run: |
          npx -p @semantic-release/commit-analyzer \
          -p @semantic-release/changelog \
          -p @semantic-release/git \
          -p @semantic-release/github \
          -p @semantic-release/release-notes-generator \
          -p semantic-release \
          semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: vincenthardouin.dev
