template: og-card/card-template.png
title:
  start:
    px: 150
    py: 230
  fgHexColor: "#0B132B"
  fontSize: 50
  fontStyle: Medium
  maxWidth: 850
author:
  enabled: false
tags:
  enabled: false
categories:
  enabled: false